#include <stdint.h>
#include <stddef.h>
#include "aster.h"
#include "graphics.h"

#define CSS_ANY_TAG 255u
#define CSS_SELECTOR_ANY 0u
#define CSS_SELECTOR_TAG 1u
#define CSS_SELECTOR_CLASS 2u
#define CSS_SELECTOR_ID 3u
#define CSS_SELECTOR_TAG_CLASS 4u
#define CSS_SELECTOR_TAG_ID 5u
typedef struct{uint8_t flags,scale,color_set;uint32_t color;} Style;
static int sp(char c){return c==' '||c=='\t'||c=='\r'||c=='\n';}
static char low(char c){return c>='A'&&c<='Z'?(char)(c+32):c;}
static int ci(const char*s,const char*p){if(!s||!p)return 0;while(*p){if(!*s||low(*s++)!=low(*p++))return 0;}return 1;}
static int eqn(const char*s,size_t n,const char*l){size_t i=0;while(i<n&&l[i]){if(low(s[i])!=low(l[i]))return 0;i++;}return i==n&&l[i]==0;}
static void cp(char*d,size_t cap,const char*s,size_t n){size_t i=0;if(!cap)return;while(i<n&&s&&s[i]&&i+1<cap){d[i]=s[i];i++;}d[i]=0;}
static int hx(char c){if(c>='0'&&c<='9')return c-'0';c=low(c);return c>='a'&&c<='f'?c-'a'+10:-1;}
static int dg(char c){return c>='0'&&c<='9';}
static uint16_t store(AsterDocument*d,const char*s,size_t n){if(!d||!s||!n||d->text_used>=ASTER_TEXT_CAP-1)return 0;size_t a=ASTER_TEXT_CAP-1-d->text_used;if(n>a)n=a;uint16_t o=d->text_used;for(size_t i=0;i<n;i++)d->text[d->text_used++]=s[i];d->text[d->text_used]=0;return o;}
static int add(AsterDocument*d,int p,uint8_t type,uint8_t tag,uint16_t off,uint16_t len){if(d->node_count>=ASTER_MAX_NODES)return -1;int i=d->node_count++;AsterNode*n=&d->nodes[i];n->type=type;n->tag=tag;n->parent=(int16_t)p;n->first_child=-1;n->next_sibling=-1;n->text_off=off;n->text_len=len;n->href_off=n->href_len=n->src_off=n->src_len=n->id_off=n->id_len=n->class_off=n->class_len=n->width_hint=n->height_hint=0;n->style_flags=n->style_scale=0;n->style_color=0;if(p>=0){AsterNode*q=&d->nodes[p];if(q->first_child<0)q->first_child=(int16_t)i;else{int c=q->first_child;while(d->nodes[c].next_sibling>=0)c=d->nodes[c].next_sibling;d->nodes[c].next_sibling=(int16_t)i;}}return i;}
static uint8_t tagid(const char*s,size_t n){
#define T(x,y) if(eqn(s,n,x))return y
T("html",ASTER_TAG_HTML);T("head",ASTER_TAG_HEAD);T("body",ASTER_TAG_BODY);T("title",ASTER_TAG_TITLE);T("h1",ASTER_TAG_H1);T("h2",ASTER_TAG_H2);T("h3",ASTER_TAG_H3);T("p",ASTER_TAG_P);T("div",ASTER_TAG_DIV);T("br",ASTER_TAG_BR);T("hr",ASTER_TAG_HR);T("a",ASTER_TAG_A);T("ul",ASTER_TAG_UL);T("ol",ASTER_TAG_OL);T("li",ASTER_TAG_LI);if(eqn(s,n,"strong")||eqn(s,n,"b"))return ASTER_TAG_STRONG;if(eqn(s,n,"em")||eqn(s,n,"i"))return ASTER_TAG_EM;T("code",ASTER_TAG_CODE);T("span",ASTER_TAG_SPAN);T("header",ASTER_TAG_HEADER);T("footer",ASTER_TAG_FOOTER);T("main",ASTER_TAG_MAIN);T("nav",ASTER_TAG_NAV);T("section",ASTER_TAG_SECTION);T("article",ASTER_TAG_ARTICLE);T("blockquote",ASTER_TAG_BLOCKQUOTE);T("script",ASTER_TAG_SCRIPT);T("style",ASTER_TAG_STYLE);T("img",ASTER_TAG_IMG);T("button",ASTER_TAG_BUTTON);
#undef T
return ASTER_TAG_UNKNOWN;}
static int block(uint8_t t){return t==ASTER_TAG_BODY||t==ASTER_TAG_H1||t==ASTER_TAG_H2||t==ASTER_TAG_H3||t==ASTER_TAG_P||t==ASTER_TAG_DIV||t==ASTER_TAG_UL||t==ASTER_TAG_OL||t==ASTER_TAG_LI||t==ASTER_TAG_HEADER||t==ASTER_TAG_FOOTER||t==ASTER_TAG_MAIN||t==ASTER_TAG_NAV||t==ASTER_TAG_SECTION||t==ASTER_TAG_ARTICLE||t==ASTER_TAG_BLOCKQUOTE||t==ASTER_TAG_HR||t==ASTER_TAG_IMG;}
static int voidtag(uint8_t t){return t==ASTER_TAG_BR||t==ASTER_TAG_HR||t==ASTER_TAG_IMG;}
void aster_document_init(AsterDocument*d){if(!d)return;d->node_count=d->paint_count=d->text_used=0;d->css_count=0;d->document_height=0;d->title[0]=0;(void)add(d,-1,ASTER_NODE_ROOT,ASTER_TAG_UNKNOWN,0,0);}
static size_t decode(char*out,size_t cap,const char*s,size_t n){size_t o=0;int ws=0;if(!cap)return 0;for(size_t i=0;i<n&&o+1<cap;i++){char c=s[i];if(c=='&'){if(i+3<n&&ci(s+i,"&lt;")){c='<';i+=3;}else if(i+3<n&&ci(s+i,"&gt;")){c='>';i+=3;}else if(i+4<n&&ci(s+i,"&amp;")){c='&';i+=4;}else if(i+5<n&&ci(s+i,"&nbsp;")){c=' ';i+=5;}else if(i+5<n&&ci(s+i,"&quot;")){c='\"';i+=5;}}if(sp(c)){ws=1;continue;}if(ws&&o)out[o++]=' ';ws=0;out[o++]=c;}out[o]=0;return o;}
static int color(const char*s,size_t n,uint32_t*out){while(n&&sp(*s)){s++;n--;}while(n&&sp(s[n-1]))n--;if(n==7&&s[0]=='#'){uint32_t v=0;for(size_t i=1;i<7;i++){int h=hx(s[i]);if(h<0)return 0;v=(v<<4)|(uint32_t)h;}*out=v;return 1;}if(eqn(s,n,"red")){*out=0xCC3344;return 1;}if(eqn(s,n,"green")){*out=0x2E8B57;return 1;}if(eqn(s,n,"blue")){*out=0x2468C4;return 1;}if(eqn(s,n,"black")){*out=0;return 1;}if(eqn(s,n,"white")){*out=0xFFFFFF;return 1;}if(eqn(s,n,"gray")||eqn(s,n,"grey")){*out=0x777777;return 1;}return 0;}
static void decl(Style*st,const char*n,size_t nn,const char*v,size_t vn){while(vn&&sp(*v)){v++;vn--;}while(vn&&sp(v[vn-1]))vn--;if(eqn(n,nn,"color")){uint32_t c;if(color(v,vn,&c)){st->color=c;st->color_set=1;}}else if(eqn(n,nn,"font-weight")&&eqn(v,vn,"bold"))st->flags|=ASTER_STYLE_BOLD;else if(eqn(n,nn,"text-decoration")&&ci(v,"underline"))st->flags|=ASTER_STYLE_UNDERLINE;else if(eqn(n,nn,"display")&&eqn(v,vn,"none"))st->flags|=ASTER_STYLE_HIDDEN;else if(eqn(n,nn,"font-size")){unsigned x=0;size_t i=0;while(i<vn&&dg(v[i]))x=x*10u+(unsigned)(v[i++]-'0');if(x>=22)st->scale=2;else if(x)st->scale=1;}}
static Style styletext(const char*s,size_t n){Style st={0,0,0,0};size_t p=0;while(p<n){while(p<n&&(sp(s[p])||s[p]==';'))p++;size_t ns=p;while(p<n&&s[p]!=':'&&s[p]!=';')p++;size_t nn=p-ns;if(p>=n||s[p]!=':'){while(p<n&&s[p]!=';')p++;continue;}p++;size_t vs=p;while(p<n&&s[p]!=';')p++;size_t vn=p-vs;while(nn&&sp(s[ns+nn-1]))nn--;decl(&st,s+ns,nn,s+vs,vn);}return st;}
static int selector(AsterDocument*d,const char*s,size_t n,AsterCssRule*r){while(n&&sp(*s)){s++;n--;}while(n&&sp(s[n-1]))n--;if(!n)return 0;for(size_t i=0;i<n;i++)if(sp(s[i])||s[i]=='>'||s[i]=='['||s[i]==':'||s[i]=='+')return 0;r->tag=CSS_ANY_TAG;r->selector_kind=CSS_SELECTOR_ANY;r->selector_off=r->selector_len=0;if(n==1&&s[0]=='*')return 1;size_t split=n;char mark=0;for(size_t i=0;i<n;i++)if(s[i]=='.'||s[i]=='#'){split=i;mark=s[i];break;}if(split==0){if(n<2)return 0;r->selector_kind=mark=='.'?CSS_SELECTOR_CLASS:CSS_SELECTOR_ID;r->selector_off=store(d,s+1,n-1);r->selector_len=(uint16_t)(n-1);return r->selector_len!=0;}uint8_t t=tagid(s,split);if(t==ASTER_TAG_UNKNOWN)return 0;r->tag=t;if(!mark){r->selector_kind=CSS_SELECTOR_TAG;return 1;}if(split+1>=n)return 0;r->selector_kind=mark=='.'?CSS_SELECTOR_TAG_CLASS:CSS_SELECTOR_TAG_ID;r->selector_off=store(d,s+split+1,n-split-1);r->selector_len=(uint16_t)(n-split-1);return r->selector_len!=0;}
static void cssadd(AsterDocument*d,const char*s,size_t n,Style st){if(d->css_count>=ASTER_MAX_CSS_RULES)return;AsterCssRule r;r.flags=st.flags;r.scale=st.scale;r.color_set=st.color_set;r.color=st.color;if(!selector(d,s,n,&r))return;d->css[d->css_count++]=r;}
static void css(AsterDocument*d,const char*s,size_t n){size_t p=0;while(p<n&&d->css_count<ASTER_MAX_CSS_RULES){while(p<n&&sp(s[p]))p++;size_t ss=p;while(p<n&&s[p]!='{')p++;if(p>=n)break;size_t sn=p-ss;p++;size_t ds=p;while(p<n&&s[p]!='}')p++;size_t dn=p-ds;if(p<n)p++;Style st=styletext(s+ds,dn);size_t q=0;while(q<sn&&d->css_count<ASTER_MAX_CSS_RULES){size_t a=q;while(q<sn&&s[ss+q]!=',')q++;cssadd(d,s+ss+a,q-a,st);if(q<sn&&s[ss+q]==',')q++;}}}
static int attr(const char*s,size_t n,const char*want,const char**v,size_t*vn){size_t i=0;while(i<n){while(i<n&&sp(s[i]))i++;size_t ns=i;while(i<n&&!sp(s[i])&&s[i]!='='&&s[i]!='>')i++;size_t nn=i-ns;while(i<n&&sp(s[i]))i++;if(i>=n||s[i]!='='){while(i<n&&!sp(s[i]))i++;continue;}i++;while(i<n&&sp(s[i]))i++;char q=0;if(i<n&&(s[i]=='\''||s[i]=='\"'))q=s[i++];size_t vs=i;if(q)while(i<n&&s[i]!=q)i++;else while(i<n&&!sp(s[i])&&s[i]!='>')i++;size_t vl=i-vs;if(q&&i<n)i++;if(eqn(s+ns,nn,want)){*v=s+vs;*vn=vl;return 1;}}return 0;}
static uint16_t dim(const char*s,size_t n){unsigned v=0;size_t i=0;while(i<n&&dg(s[i])){v=v*10u+(unsigned)(s[i++]-'0');if(v>4096)v=4096;}return (uint16_t)v;}
static void attrs(AsterDocument*d,AsterNode*n,const char*s,size_t len){const char*v;size_t z;if(attr(s,len,"href",&v,&z)&&z){n->href_off=store(d,v,z);n->href_len=(uint16_t)z;}if(attr(s,len,"src",&v,&z)&&z){n->src_off=store(d,v,z);n->src_len=(uint16_t)z;}if(attr(s,len,"id",&v,&z)&&z){n->id_off=store(d,v,z);n->id_len=(uint16_t)z;}if(attr(s,len,"class",&v,&z)&&z){n->class_off=store(d,v,z);n->class_len=(uint16_t)z;}if(attr(s,len,"alt",&v,&z)&&z){char t[192];size_t m=decode(t,sizeof(t),v,z);n->text_off=store(d,t,m);n->text_len=(uint16_t)m;}if(attr(s,len,"width",&v,&z))n->width_hint=dim(v,z);if(attr(s,len,"height",&v,&z))n->height_hint=dim(v,z);if(attr(s,len,"style",&v,&z)){Style st=styletext(v,z);n->style_flags=st.flags;n->style_scale=st.scale;n->style_color=st.color_set?st.color:0;}}
static const char*closep(const char*p,const char*e){while(*p&&!ci(p,e))p++;return p;}
int aster_parse_html(AsterDocument*d,const char*h){if(!d||!h)return 0;aster_document_init(d);int st[48],spn=1;st[0]=0;const char*p=h;while(*p&&d->node_count<ASTER_MAX_NODES){if(*p!='<'){const char*s=p;while(*p&&*p!='<')p++;char t[768];size_t n=decode(t,sizeof(t),s,(size_t)(p-s));if(n){uint16_t o=store(d,t,n);int i=add(d,st[spn-1],ASTER_NODE_TEXT,ASTER_TAG_UNKNOWN,o,(uint16_t)n);if(i>=0&&d->nodes[st[spn-1]].tag==ASTER_TAG_TITLE&&!d->title[0])cp(d->title,sizeof(d->title),t,n);}continue;}if(ci(p,"<!--")){p+=4;while(*p&&!(p[0]=='-'&&p[1]=='-'&&p[2]=='>'))p++;if(*p)p+=3;continue;}if(p[1]=='!'||p[1]=='?'){while(*p&&*p!='>')p++;if(*p)p++;continue;}p++;int cl=0;if(*p=='/'){cl=1;p++;}while(*p&&sp(*p))p++;const char*n=p;while(*p&&!sp(*p)&&*p!='>'&&*p!='/')p++;size_t nn=(size_t)(p-n);uint8_t t=tagid(n,nn);if(cl){while(*p&&*p!='>')p++;if(*p)p++;for(int i=spn-1;i>0;i--)if(d->nodes[st[i]].tag==t){spn=i;break;}continue;}const char*a=p;while(*p&&*p!='>')p++;size_t an=(size_t)(p-a),trim=an;while(trim&&sp(a[trim-1]))trim--;int self=trim&&a[trim-1]=='/';if(*p)p++;int idx=add(d,st[spn-1],ASTER_NODE_ELEMENT,t,0,0);if(idx<0)break;attrs(d,&d->nodes[idx],a,an);if(t==ASTER_TAG_STYLE){const char*e=closep(p,"</style");css(d,p,(size_t)(e-p));p=e;if(*p){while(*p&&*p!='>')p++;if(*p)p++;}continue;}if(t==ASTER_TAG_SCRIPT){const char*e=closep(p,"</script");p=e;if(*p){while(*p&&*p!='>')p++;if(*p)p++;}continue;}if(!self&&!voidtag(t)&&spn<(int)(sizeof(st)/sizeof(st[0])))st[spn++]=idx;}if(!d->title[0])cp(d->title,sizeof(d->title),"Untitled page",13);return d->node_count>1;}
static int inh(const AsterDocument*d,int n,uint8_t t){for(;n>=0;n=d->nodes[n].parent)if(d->nodes[n].tag==t)return 1;return 0;}
static const AsterNode*link(const AsterDocument*d,int n){for(;n>=0;n=d->nodes[n].parent)if(d->nodes[n].tag==ASTER_TAG_A&&d->nodes[n].href_len)return &d->nodes[n];return 0;}
static int teq(const AsterDocument*d,uint16_t a,uint16_t an,uint16_t b,uint16_t bn){if(an!=bn||(size_t)a+an>ASTER_TEXT_CAP||(size_t)b+bn>ASTER_TEXT_CAP)return 0;for(uint16_t i=0;i<an;i++)if(d->text[a+i]!=d->text[b+i])return 0;return 1;}
static int hasclass(const AsterDocument*d,const AsterNode*n,const AsterCssRule*r){if(!n->class_len||(size_t)n->class_off+n->class_len>ASTER_TEXT_CAP)return 0;uint16_t p=0;while(p<n->class_len){while(p<n->class_len&&sp(d->text[n->class_off+p]))p++;uint16_t a=p;while(p<n->class_len&&!sp(d->text[n->class_off+p]))p++;uint16_t z=(uint16_t)(p-a);if(z==r->selector_len){int ok=1;for(uint16_t i=0;i<z;i++)if(d->text[n->class_off+a+i]!=d->text[r->selector_off+i]){ok=0;break;}if(ok)return 1;}}return 0;}
static int matches(const AsterDocument*d,const AsterCssRule*r,const AsterNode*n){if(r->tag!=CSS_ANY_TAG&&r->tag!=n->tag)return 0;switch(r->selector_kind){case CSS_SELECTOR_ANY:case CSS_SELECTOR_TAG:return 1;case CSS_SELECTOR_CLASS:case CSS_SELECTOR_TAG_CLASS:return hasclass(d,n,r);case CSS_SELECTOR_ID:case CSS_SELECTOR_TAG_ID:return n->id_len&&teq(d,n->id_off,n->id_len,r->selector_off,r->selector_len);default:return 0;}}
static uint8_t specof(const AsterCssRule*r){switch(r->selector_kind){case CSS_SELECTOR_ID:return 100;case CSS_SELECTOR_TAG_ID:return 101;case CSS_SELECTOR_CLASS:return 10;case CSS_SELECTOR_TAG_CLASS:return 11;case CSS_SELECTOR_TAG:return 1;default:return 0;}}
static void rules(const AsterDocument*d,int node,Style*st){const AsterNode*n=&d->nodes[node];uint8_t cs=0,ss=0;int co=-1,so=-1;for(uint8_t i=0;i<d->css_count;i++){const AsterCssRule*r=&d->css[i];if(!matches(d,r,n))continue;uint8_t spc=specof(r);st->flags|=r->flags;if(r->scale&&(spc>ss||(spc==ss&&(int)i>=so))){st->scale=r->scale;ss=spc;so=i;}if(r->color_set&&(spc>cs||(spc==cs&&(int)i>=co))){st->color=r->color;st->color_set=1;cs=spc;co=i;}}}
static Style resolved(const AsterDocument*d,int n){Style st={0,1,0,0x26394B};if(inh(d,n,ASTER_TAG_H1)){st.scale=2;st.flags|=ASTER_STYLE_BOLD;st.color=0x1D3550;st.color_set=1;}else if(inh(d,n,ASTER_TAG_H2)||inh(d,n,ASTER_TAG_H3))st.flags|=ASTER_STYLE_BOLD;if(inh(d,n,ASTER_TAG_STRONG))st.flags|=ASTER_STYLE_BOLD;if(inh(d,n,ASTER_TAG_CODE)){st.color=0x7B3F57;st.color_set=1;}int chain[48],count=0;for(int x=n;x>=0&&count<48;x=d->nodes[x].parent)chain[count++]=x;for(int i=count-1;i>=0;i--){const AsterNode*q=&d->nodes[chain[i]];rules(d,chain[i],&st);st.flags|=q->style_flags;if(q->style_scale)st.scale=q->style_scale;if(q->style_color){st.color=q->style_color;st.color_set=1;}}return st;}
static int hidden(const AsterDocument*d,int n){if(inh(d,n,ASTER_TAG_HEAD)||inh(d,n,ASTER_TAG_TITLE)||inh(d,n,ASTER_TAG_SCRIPT)||inh(d,n,ASTER_TAG_STYLE))return 1;return (resolved(d,n).flags&ASTER_STYLE_HIDDEN)!=0;}
static void emit(AsterDocument*d,int x,int y,int w,int h,uint8_t scale,uint8_t flags,uint32_t col,uint16_t off,uint16_t len,const AsterNode*l,uint16_t so,uint16_t sl){if(d->paint_count>=ASTER_MAX_PAINT)return;AsterPaintItem*i=&d->paint[d->paint_count++];i->x=(int16_t)x;i->y=(int16_t)y;i->w=(int16_t)w;i->h=(int16_t)h;i->scale=scale;i->flags=flags;i->color=col;i->text_off=off;i->text_len=len;i->href_off=l?l->href_off:0;i->href_len=l?l->href_len:0;i->src_off=so;i->src_len=sl;}
static int cw(uint8_t s){return s==2?24:11;}static int lh(uint8_t s){return s==2?52:24;}
static void textnode(AsterDocument*d,int n,int*cx,int*cy,int left,int width){AsterNode*q=&d->nodes[n];Style st=resolved(d,n);uint8_t fl=0;if(st.flags&ASTER_STYLE_BOLD)fl|=ASTER_PAINT_BOLD;if(st.flags&ASTER_STYLE_UNDERLINE)fl|=ASTER_PAINT_UNDERLINE;const AsterNode*l=link(d,n);if(l)fl|=ASTER_PAINT_LINK;uint32_t col=st.color_set?st.color:(l?0x2F74B7:0x26394B);int c=cw(st.scale),line=lh(st.scale),right=left+width;uint16_t p=0;const char*s=d->text+q->text_off;if(*cx<left)*cx=left;while(p<q->text_len){while(p<q->text_len&&s[p]==' ')p++;if(p>=q->text_len)break;uint16_t a=p;while(p<q->text_len&&s[p]!=' ')p++;int ww=(int)(p-a)*c;if(*cx>left&&*cx+ww>right){*cx=left;*cy+=line;}emit(d,*cx,*cy,ww,line,st.scale,fl,col,(uint16_t)(q->text_off+a),(uint16_t)(p-a),l,0,0);*cx+=ww+c;}}
static void walk(AsterDocument*d,int n,int*cx,int*cy,int left,int width){if(n<0||hidden(d,n))return;AsterNode*q=&d->nodes[n];uint8_t t=q->tag;int b=block(t);if(b&&*cx!=left){*cx=left;*cy+=24;}if(t==ASTER_TAG_H1||t==ASTER_TAG_H2||t==ASTER_TAG_H3||t==ASTER_TAG_P||t==ASTER_TAG_DIV||t==ASTER_TAG_LI||t==ASTER_TAG_SECTION||t==ASTER_TAG_ARTICLE||t==ASTER_TAG_BLOCKQUOTE)*cy+=8;int cl=left,cw2=width;if(t==ASTER_TAG_LI){cl=left+22;cw2=width>22?width-22:width;*cx=cl;}else if(t==ASTER_TAG_BLOCKQUOTE){cl=left+28;cw2=width>56?width-56:width;*cx=cl;}if(q->type==ASTER_NODE_TEXT)textnode(d,n,cx,cy,left,width);if(t==ASTER_TAG_BR){*cx=left;*cy+=24;}if(t==ASTER_TAG_HR){*cx=left;*cy+=12;}if(t==ASTER_TAG_IMG){int w=q->width_hint?q->width_hint:(width>320?320:width);int h=q->height_hint?q->height_hint:180;if(w>width)w=width;if(h>360)h=360;emit(d,left,*cy,w,h,1,ASTER_PAINT_IMAGE,0xDDE6EE,q->text_off,q->text_len,link(d,n),q->src_off,q->src_len);*cx=left;*cy+=h+12;}for(int c=q->first_child;c>=0;c=d->nodes[c].next_sibling)walk(d,c,cx,cy,cl,cw2);if(b&&q->type==ASTER_NODE_ELEMENT){*cx=left;*cy+=t==ASTER_TAG_H1?20:(t==ASTER_TAG_H2?14:(t==ASTER_TAG_H3?10:8));}}
void aster_layout(AsterDocument*d,int width){if(!d)return;if(width<120)width=120;d->paint_count=0;int x=0,y=0;walk(d,0,&x,&y,0,width);d->document_height=y+32;}
void aster_paint(const AsterDocument*d,int x,int y,int width,int height,int scroll){if(!d)return;for(uint16_t k=0;k<d->paint_count;k++){const AsterPaintItem*i=&d->paint[k];int py=y+i->y-scroll;if(py+i->h<y||py>y+height||i->x>=width||i->x+i->w<0)continue;if(i->flags&ASTER_PAINT_IMAGE){char uri[256];size_t n=i->src_len<sizeof(uri)-1?i->src_len:sizeof(uri)-1;for(size_t j=0;j<n;j++)uri[j]=d->text[i->src_off+j];uri[n]=0;if(!uri[0]||!gfx_image_uri((uint32_t)(x+i->x),(uint32_t)py,(uint32_t)i->w,(uint32_t)i->h,uri)){gfx_rect((uint32_t)(x+i->x),(uint32_t)py,(uint32_t)i->w,(uint32_t)i->h,0xE7EDF3);char alt[96];n=i->text_len<sizeof(alt)-1?i->text_len:sizeof(alt)-1;for(size_t j=0;j<n;j++)alt[j]=d->text[i->text_off+j];alt[n]=0;gfx_text((uint32_t)(x+i->x+8),(uint32_t)(py+8),alt[0]?alt:"[image]",0x60758A,1);}continue;}char t[160];size_t n=i->text_len<sizeof(t)-1?i->text_len:sizeof(t)-1;for(size_t j=0;j<n;j++)t[j]=d->text[i->text_off+j];t[n]=0;uint32_t drawn=i->scale==2?gfx_display_text((uint32_t)(x+i->x),(uint32_t)py,t,i->color):gfx_text((uint32_t)(x+i->x),(uint32_t)py,t,i->color,1);if((i->flags&(ASTER_PAINT_LINK|ASTER_PAINT_UNDERLINE))!=0)gfx_line_h((uint32_t)(x+i->x),(uint32_t)(py+i->h-4),drawn,(i->flags&ASTER_PAINT_LINK)?0x6BA5D8:i->color);}}
int aster_link_at(const AsterDocument*d,int x,int y,int scroll,char*u,size_t cap){if(!d||!u||!cap)return 0;u[0]=0;int yy=y+scroll;for(int k=(int)d->paint_count-1;k>=0;k--){const AsterPaintItem*i=&d->paint[k];if(!i->href_len)continue;if(x<i->x||x>=i->x+i->w||yy<i->y||yy>=i->y+i->h)continue;size_t n=i->href_len;if(n>=cap)n=cap-1;for(size_t j=0;j<n;j++)u[j]=d->text[i->href_off+j];u[n]=0;return 1;}return 0;}
int aster_document_height(const AsterDocument*d){return d?d->document_height:0;}uint32_t aster_api_version(void){return ASTER_API_VERSION;}const char*aster_version(void){return ASTER_VERSION;}
