#include <stddef.h>
#include <stdint.h>
#include <bearssl.h>
#include "io.h"
#include "net.h"
#include "serial.h"
#include "tls.h"
#include "orion_trust_anchors.c"

static br_ssl_client_context tls_sc;
static br_x509_minimal_context tls_xc;
static unsigned char tls_iobuf[BR_SSL_BUFSIZE_MONO];

static void scopy(char*d,size_t cap,const char*s){size_t i=0;if(!d||!cap)return;while(s&&s[i]&&i+1<cap){d[i]=s[i];i++;}d[i]=0;}
static char lower_ascii(char c){return c>='A'&&c<='Z'?(char)(c+32):c;}
static int span_eq_ci(const uint8_t*s,size_t n,const char*lit){size_t i=0;while(i<n&&lit[i]){if(lower_ascii((char)s[i])!=lower_ascii(lit[i]))return 0;i++;}return i==n&&lit[i]==0;}
static void tls_log_error(const char *stage,unsigned err){serial_write("TLS: ");serial_write(stage);serial_write(" error=");serial_write_hex64((uint64_t)err);serial_write("\r\n");}

/* Return 1 when a complete HTTP message has been authenticated, 0 while more
 * bytes are needed, and -1 for malformed framing. This lets HTTPS stop safely
 * after Content-Length/chunked completion without treating every BR_ERR_IO as
 * success; an abrupt EOF before the authenticated message boundary still fails. */
static int header_boundary(const uint8_t*b,size_t n,size_t*head_end,size_t*body_off){for(size_t i=0;i+3<n;i++){if(b[i]=='\r'&&b[i+1]=='\n'&&b[i+2]=='\r'&&b[i+3]=='\n'){*head_end=i;*body_off=i+4;return 1;}}for(size_t i=0;i+1<n;i++){if(b[i]=='\n'&&b[i+1]=='\n'){*head_end=i;*body_off=i+2;return 1;}}return 0;}
static int value_has_chunked(const uint8_t*s,size_t n){size_t p=0;while(p<n){while(p<n&&(s[p]==' '||s[p]=='\t'||s[p]==','))p++;size_t a=p;while(p<n&&s[p]!=','&&s[p]!=';'&&s[p]!=' '&&s[p]!='\t')p++;if(span_eq_ci(s+a,p-a,"chunked"))return 1;while(p<n&&s[p]!=',')p++;}return 0;}
static int parse_dec(const uint8_t*s,size_t n,size_t*out){size_t p=0,v=0;while(p<n&&(s[p]==' '||s[p]=='\t'))p++;size_t digits=0;while(p<n&&s[p]>='0'&&s[p]<='9'){unsigned d=(unsigned)(s[p]-'0');if(v>((size_t)-1-d)/10u)return 0;v=v*10u+d;p++;digits++;}while(p<n&&(s[p]==' '||s[p]=='\t'))p++;if(!digits||p!=n)return 0;*out=v;return 1;}
static int parse_status(const uint8_t*b,size_t n){size_t p=0;while(p<n&&b[p]!=' '&&b[p]!='\r'&&b[p]!='\n')p++;while(p<n&&b[p]==' ')p++;if(p+2>=n||b[p]<'0'||b[p]>'9'||b[p+1]<'0'||b[p+1]>'9'||b[p+2]<'0'||b[p+2]>'9')return -1;return (b[p]-'0')*100+(b[p+1]-'0')*10+(b[p+2]-'0');}
static int chunked_complete(const uint8_t*b,size_t n,size_t p){for(;;){size_t le=p;while(le<n&&b[le]!='\n')le++;if(le>=n)return 0;size_t q=p,end=le;if(end>p&&b[end-1]=='\r')end--;while(q<end&&(b[q]==' '||b[q]=='\t'))q++;size_t size=0,digits=0;while(q<end){uint8_t c=b[q];unsigned v;if(c>='0'&&c<='9')v=(unsigned)(c-'0');else if(c>='a'&&c<='f')v=(unsigned)(c-'a'+10);else if(c>='A'&&c<='F')v=(unsigned)(c-'A'+10);else break;if(size>((size_t)-1-v)/16u)return -1;size=size*16u+v;q++;digits++;}if(!digits)return -1;while(q<end&&(b[q]==' '||b[q]=='\t'))q++;if(q<end&&b[q]!=';')return -1;p=le+1;if(size==0){for(;;){if(p>=n)return 0;size_t te=p;while(te<n&&b[te]!='\n')te++;if(te>=n)return 0;size_t tl=te-p;if(tl&&b[te-1]=='\r')tl--;p=te+1;if(tl==0)return 1;}}if(size>n-p)return 0;p+=size;if(p>=n)return 0;if(b[p]=='\r'){if(p+1>=n)return 0;if(b[p+1]!='\n')return -1;p+=2;}else if(b[p]=='\n')p++;else return -1;}}
static int http_frame_complete(const uint8_t*b,size_t n){size_t he=0,bo=0;if(!header_boundary(b,n,&he,&bo))return 0;int code=parse_status(b,he);if(code<0)return -1;if(code==204||code==304)return 1;int chunked=0,have_len=0;size_t content_len=0;size_t p=0;while(p<he&&b[p]!='\n')p++;if(p<he)p++;while(p<he){size_t le=p;while(le<he&&b[le]!='\n')le++;size_t end=le;if(end>p&&b[end-1]=='\r')end--;size_t colon=p;while(colon<end&&b[colon]!=':')colon++;if(colon<end){size_t ne=colon;while(ne>p&&(b[ne-1]==' '||b[ne-1]=='\t'))ne--;size_t vs=colon+1;while(vs<end&&(b[vs]==' '||b[vs]=='\t'))vs++;size_t ve=end;while(ve>vs&&(b[ve-1]==' '||b[ve-1]=='\t'))ve--;if(span_eq_ci(b+p,ne-p,"Transfer-Encoding")){if(value_has_chunked(b+vs,ve-vs))chunked=1;}else if(span_eq_ci(b+p,ne-p,"Content-Length")){size_t v;if(!parse_dec(b+vs,ve-vs,&v))return -1;if(have_len&&v!=content_len)return -1;content_len=v;have_len=1;}}p=le<he?le+1:he;}if(chunked)return chunked_complete(b,n,bo);if(have_len){if(content_len>(size_t)-1-bo)return -1;return n>=bo+content_len?1:0;}return 0;}

static void cpuid1(uint32_t *ecx){uint32_t a=1,b,c=0,d;__asm__ volatile("cpuid":"=a"(a),"=b"(b),"=c"(c),"=d"(d):"a"(a),"c"(c));(void)b;(void)d;*ecx=c;}
static int entropy_bytes(uint8_t *out,size_t len){uint32_t ecx=0;cpuid1(&ecx);if(!(ecx&(1u<<30)))return 0;size_t o=0;while(o<len){unsigned long v=0;unsigned char ok=0;for(int tries=0;tries<16&&!ok;tries++)__asm__ volatile("rdrand %0; setc %1":"=r"(v),"=qm"(ok));if(!ok)return 0;for(size_t i=0;i<sizeof(v)&&o<len;i++,o++)out[o]=(uint8_t)(v>>(i*8));}return 1;}
static uint8_t cmos(uint8_t reg){outb(0x70,(uint8_t)(0x80u|reg));io_wait();return inb(0x71);}
static int rtc_snapshot(uint8_t *sec,uint8_t *min,uint8_t *hour,uint8_t *day,uint8_t *mon,uint8_t *year,uint8_t *cent,uint8_t *regb){for(int retry=0;retry<8;retry++){while(cmos(0x0A)&0x80u){}uint8_t s1=cmos(0),m1=cmos(2),h1=cmos(4),d1=cmos(7),mo1=cmos(8),y1=cmos(9),c1=cmos(0x32),b1=cmos(0x0B);while(cmos(0x0A)&0x80u){}uint8_t s2=cmos(0),m2=cmos(2),h2=cmos(4),d2=cmos(7),mo2=cmos(8),y2=cmos(9),c2=cmos(0x32),b2=cmos(0x0B);if(s1==s2&&m1==m2&&h1==h2&&d1==d2&&mo1==mo2&&y1==y2&&c1==c2&&b1==b2){*sec=s2;*min=m2;*hour=h2;*day=d2;*mon=mo2;*year=y2;*cent=c2;*regb=b2;return 1;}}return 0;}
static unsigned bcd(unsigned x){return (x&15u)+10u*((x>>4)&15u);}
static int leap(int y){return (y%4==0&&y%100!=0)||y%400==0;}
static int tls_time(uint32_t *days,uint32_t *seconds){uint8_t s,m,h,d,mo,y,c,b;if(!rtc_snapshot(&s,&m,&h,&d,&mo,&y,&c,&b))return 0;int pm=(h&0x80u)!=0;h&=0x7fu;if(!(b&0x04u)){s=(uint8_t)bcd(s);m=(uint8_t)bcd(m);h=(uint8_t)bcd(h);d=(uint8_t)bcd(d);mo=(uint8_t)bcd(mo);y=(uint8_t)bcd(y);c=(uint8_t)bcd(c);}if(!(b&0x02u)){if(pm&&h<12)h=(uint8_t)(h+12);if(!pm&&h==12)h=0;}int yy;if(c>=19&&c<=99)yy=(int)c*100+(int)y;else yy=y<70?2000+(int)y:1900+(int)y;if(yy<2020||yy>2199||mo<1||mo>12||d<1||d>31||h>23||m>59||s>60)return 0;static const uint8_t md[12]={31,28,31,30,31,30,31,31,30,31,30,31};uint32_t unix_days=0;for(int z=1970;z<yy;z++)unix_days+=(uint32_t)(leap(z)?366:365);for(int z=1;z<(int)mo;z++)unix_days+=(uint32_t)(md[z-1]+(z==2&&leap(yy)?1:0));unsigned maxd=md[mo-1]+(mo==2&&leap(yy)?1u:0u);if(d>maxd)return 0;unix_days+=(uint32_t)d-1u;*days=719528u+unix_days;*seconds=(uint32_t)h*3600u+(uint32_t)m*60u+(uint32_t)s;return 1;}
static int low_read(void *ctx,unsigned char *data,size_t len){(void)ctx;int n=net_tcp_read(data,len,10000);return n>0?n:-1;}
static int low_write(void *ctx,const unsigned char *data,size_t len){(void)ctx;size_t n=len>1200?1200:len;return net_tcp_write(data,n,6000)?(int)n:-1;}

int tls_platform_ready(char *status,size_t status_cap){uint8_t seed[8];uint32_t d,s;if(!entropy_bytes(seed,sizeof(seed))){scopy(status,status_cap,"TLS needs x86 RDRAND entropy");return 0;}if(!tls_time(&d,&s)){scopy(status,status_cap,"TLS needs a valid RTC clock");return 0;}return 1;}

int tls_https_exchange(const char *host,uint16_t port,const uint8_t *request,size_t request_len,uint8_t *response,size_t response_cap,size_t *response_len,char *status,size_t status_cap){if(response_len)*response_len=0;if(!host||!*host||!request||!response||response_cap<2)return 0;uint8_t seed[48];uint32_t days,seconds;if(!entropy_bytes(seed,sizeof(seed))){serial_write("TLS: RDRAND entropy unavailable\r\n");scopy(status,status_cap,"TLS entropy unavailable");return 0;}if(!tls_time(&days,&seconds)){serial_write("TLS: RTC clock unavailable\r\n");scopy(status,status_cap,"TLS clock unavailable");return 0;}serial_write("TLS: TCP connect\r\n");if(!net_tcp_connect(host,port,status,status_cap)){serial_write("TLS: TCP connect failed\r\n");return 0;}serial_write("TLS: starting verified TLS 1.2 handshake\r\n");br_ssl_client_init_full(&tls_sc,&tls_xc,TAs,TAs_NUM);br_ssl_engine_set_versions(&tls_sc.eng,BR_TLS12,BR_TLS12);br_ssl_engine_set_buffer(&tls_sc.eng,tls_iobuf,sizeof(tls_iobuf),0);br_ssl_engine_inject_entropy(&tls_sc.eng,seed,sizeof(seed));br_x509_minimal_set_time(&tls_xc,days,seconds);br_x509_minimal_set_minrsa(&tls_xc,2048);br_ssl_engine_add_flags(&tls_sc.eng,BR_OPT_NO_RENEGOTIATION);if(!br_ssl_client_reset(&tls_sc,host,0)){unsigned err=br_ssl_engine_last_error(&tls_sc.eng);tls_log_error("client reset",err);net_tcp_close();scopy(status,status_cap,"TLS client reset failed");return 0;}br_sslio_context io;br_sslio_init(&io,&tls_sc.eng,low_read,0,low_write,0);if(br_sslio_write_all(&io,request,request_len)<0||br_sslio_flush(&io)<0){unsigned err=br_ssl_engine_last_error(&tls_sc.eng);tls_log_error("handshake/write",err);net_tcp_close();scopy(status,status_cap,"TLS handshake/write failed");return 0;}serial_write("TLS: request encrypted and sent\r\n");size_t used=0;int framed=0;for(;;){if(used+1>=response_cap){net_tcp_close();scopy(status,status_cap,"HTTPS response too large");return 0;}int n=br_sslio_read(&io,response+used,response_cap-1-used);if(n<0)break;used+=(size_t)n;int fs=http_frame_complete(response,used);if(fs<0){net_tcp_close();scopy(status,status_cap,"Malformed HTTPS response framing");return 0;}if(fs>0){framed=1;serial_write("TLS: complete authenticated HTTP frame\r\n");break;}}unsigned err=br_ssl_engine_last_error(&tls_sc.eng);if(!framed&&err!=BR_ERR_OK){tls_log_error("validation/transport",err);net_tcp_close();scopy(status,status_cap,"TLS validation or transport failed");return 0;}if(!framed&&used==0){net_tcp_close();scopy(status,status_cap,"Empty HTTPS response");return 0;}if(framed&&err!=BR_ERR_OK){tls_log_error("post-frame",err);net_tcp_close();scopy(status,status_cap,"TLS failed before framed response completion");return 0;}net_tcp_close();response[used]=0;if(response_len)*response_len=used;scopy(status,status_cap,"TLS 1.2 verified");serial_write("TLS: verified HTTPS session\r\n");return 1;}
