#include <stddef.h>
#include <stdint.h>
#include <bearssl.h>
#include "io.h"
#include "net.h"
#include "serial.h"
#include "tls.h"
#include "orion_trust_anchors.c"

static br_ssl_client_context tls_sc;
static br_x509_minimal_context tls_xc;
static unsigned char tls_iobuf[BR_SSL_BUFSIZE_MONO];
static void scopy(char*d,size_t cap,const char*s){size_t i=0;if(!d||!cap)return;while(s&&s[i]&&i+1<cap){d[i]=s[i];i++;}d[i]=0;}
static void tls_log_error(const char *stage,unsigned err){serial_write("TLS: ");serial_write(stage);serial_write(" error=");serial_write_hex64((uint64_t)err);serial_write("\r\n");}
static void cpuid1(uint32_t *ecx){uint32_t a=1,b,c=0,d;__asm__ volatile("cpuid":"=a"(a),"=b"(b),"=c"(c),"=d"(d):"a"(a),"c"(c));(void)b;(void)d;*ecx=c;}
static int entropy_bytes(uint8_t *out,size_t len){uint32_t ecx=0;cpuid1(&ecx);if(!(ecx&(1u<<30)))return 0;size_t o=0;while(o<len){unsigned long v=0;unsigned char ok=0;for(int tries=0;tries<16&&!ok;tries++)__asm__ volatile("rdrand %0; setc %1":"=r"(v),"=qm"(ok));if(!ok)return 0;for(size_t i=0;i<sizeof(v)&&o<len;i++,o++)out[o]=(uint8_t)(v>>(i*8));}return 1;}
static uint8_t cmos(uint8_t reg){outb(0x70,(uint8_t)(0x80u|reg));io_wait();return inb(0x71);}
static int rtc_snapshot(uint8_t *sec,uint8_t *min,uint8_t *hour,uint8_t *day,uint8_t *mon,uint8_t *year,uint8_t *cent,uint8_t *regb){for(int retry=0;retry<8;retry++){while(cmos(0x0A)&0x80u){}uint8_t s1=cmos(0),m1=cmos(2),h1=cmos(4),d1=cmos(7),mo1=cmos(8),y1=cmos(9),c1=cmos(0x32),b1=cmos(0x0B);while(cmos(0x0A)&0x80u){}uint8_t s2=cmos(0),m2=cmos(2),h2=cmos(4),d2=cmos(7),mo2=cmos(8),y2=cmos(9),c2=cmos(0x32),b2=cmos(0x0B);if(s1==s2&&m1==m2&&h1==h2&&d1==d2&&mo1==mo2&&y1==y2&&c1==c2&&b1==b2){*sec=s2;*min=m2;*hour=h2;*day=d2;*mon=mo2;*year=y2;*cent=c2;*regb=b2;return 1;}}return 0;}
static unsigned bcd(unsigned x){return (x&15u)+10u*((x>>4)&15u);}
static int leap(int y){return (y%4==0&&y%100!=0)||y%400==0;}
static int tls_time(uint32_t *days,uint32_t *seconds){uint8_t s,m,h,d,mo,y,c,b;if(!rtc_snapshot(&s,&m,&h,&d,&mo,&y,&c,&b))return 0;int pm=(h&0x80u)!=0;h&=0x7fu;if(!(b&0x04u)){s=(uint8_t)bcd(s);m=(uint8_t)bcd(m);h=(uint8_t)bcd(h);d=(uint8_t)bcd(d);mo=(uint8_t)bcd(mo);y=(uint8_t)bcd(y);c=(uint8_t)bcd(c);}if(!(b&0x02u)){if(pm&&h<12)h=(uint8_t)(h+12);if(!pm&&h==12)h=0;}int yy;if(c>=19&&c<=99)yy=(int)c*100+(int)y;else yy=y<70?2000+(int)y:1900+(int)y;if(yy<2020||yy>2199||mo<1||mo>12||d<1||d>31||h>23||m>59||s>60)return 0;static const uint8_t md[12]={31,28,31,30,31,30,31,31,30,31,30,31};uint32_t unix_days=0;for(int z=1970;z<yy;z++)unix_days+=(uint32_t)(leap(z)?366:365);for(int z=1;z<(int)mo;z++)unix_days+=(uint32_t)(md[z-1]+(z==2&&leap(yy)?1:0));unsigned maxd=md[mo-1]+(mo==2&&leap(yy)?1u:0u);if(d>maxd)return 0;unix_days+=(uint32_t)d-1u;*days=719528u+unix_days;*seconds=(uint32_t)h*3600u+(uint32_t)m*60u+(uint32_t)s;return 1;}
static int low_read(void *ctx,unsigned char *data,size_t len){(void)ctx;int n=net_tcp_read(data,len,10000);return n>0?n:-1;}
static int low_write(void *ctx,const unsigned char *data,size_t len){(void)ctx;size_t n=len>1200?1200:len;return net_tcp_write(data,n,6000)?(int)n:-1;}
int tls_platform_ready(char *status,size_t status_cap){uint8_t seed[8];uint32_t d,s;if(!entropy_bytes(seed,sizeof(seed))){scopy(status,status_cap,"TLS needs x86 RDRAND entropy");return 0;}if(!tls_time(&d,&s)){scopy(status,status_cap,"TLS needs a valid RTC clock");return 0;}return 1;}
int tls_https_exchange(const char *host,uint16_t port,const uint8_t *request,size_t request_len,uint8_t *response,size_t response_cap,size_t *response_len,char *status,size_t status_cap){if(response_len)*response_len=0;if(!host||!*host||!request||!response||response_cap<2)return 0;uint8_t seed[48];uint32_t days,seconds;if(!entropy_bytes(seed,sizeof(seed))){serial_write("TLS: RDRAND entropy unavailable\r\n");scopy(status,status_cap,"TLS entropy unavailable");return 0;}if(!tls_time(&days,&seconds)){serial_write("TLS: RTC clock unavailable\r\n");scopy(status,status_cap,"TLS clock unavailable");return 0;}serial_write("TLS: TCP connect\r\n");if(!net_tcp_connect(host,port,status,status_cap)){serial_write("TLS: TCP connect failed\r\n");return 0;}serial_write("TLS: starting verified TLS 1.2 handshake\r\n");br_ssl_client_init_full(&tls_sc,&tls_xc,TAs,TAs_NUM);br_ssl_engine_set_versions(&tls_sc.eng,BR_TLS12,BR_TLS12);br_ssl_engine_set_buffer(&tls_sc.eng,tls_iobuf,sizeof(tls_iobuf),0);br_ssl_engine_inject_entropy(&tls_sc.eng,seed,sizeof(seed));br_x509_minimal_set_time(&tls_xc,days,seconds);br_x509_minimal_set_minrsa(&tls_xc,256);br_ssl_engine_add_flags(&tls_sc.eng,BR_OPT_NO_RENEGOTIATION);if(!br_ssl_client_reset(&tls_sc,host,0)){unsigned err=br_ssl_engine_last_error(&tls_sc.eng);tls_log_error("client reset",err);net_tcp_close();scopy(status,status_cap,"TLS client reset failed");return 0;}br_sslio_context io;br_sslio_init(&io,&tls_sc.eng,low_read,0,low_write,0);if(br_sslio_write_all(&io,request,request_len)<0||br_sslio_flush(&io)<0){unsigned err=br_ssl_engine_last_error(&tls_sc.eng);tls_log_error("handshake/write",err);net_tcp_close();scopy(status,status_cap,"TLS handshake/write failed");return 0;}serial_write("TLS: request encrypted and sent\r\n");size_t used=0;for(;;){if(used+1>=response_cap){net_tcp_close();scopy(status,status_cap,"HTTPS response too large");return 0;}int n=br_sslio_read(&io,response+used,response_cap-1-used);if(n<0)break;used+=(size_t)n;}unsigned err=br_ssl_engine_last_error(&tls_sc.eng);net_tcp_close();if(err!=BR_ERR_OK){tls_log_error("validation/transport",err);scopy(status,status_cap,"TLS validation or transport failed");return 0;}response[used]=0;if(response_len)*response_len=used;scopy(status,status_cap,"TLS 1.2 verified");serial_write("TLS: verified HTTPS session\r\n");return used>0;}
